In [4]:
import pandas as pd

In [1]:
from DeepRetail.data.dataloader import Reader

In [2]:
case_filepath = "/home/filtheo/Data_folder/M5/Accuracy/sales_train_validation.csv"
calendar = "/home/filtheo/Data_folder/M5/Accuracy/calendar.csv"
out_path = "/home/filtheo/DeepRetail/DeepRetail/data/data_folder/m5_day.csv"

# Call the reader
r = Reader(case=0, filepath=case_filepath,calendar_filepath=calendar)
r.save(out_path, frequency="D", format="pivoted", calendar_filepath=calendar)

Loading completed. Saving.

In [5]:
df = pd.read_csv('/home/filtheo/DeepRetail/DeepRetail/data/data_folder/m5_day.csv', index_col=0)
df.head()

,2011-01-29,2011-01-30,2011-01-31,2011-02-01,2011-02-02,2011-02-03,2011-02-04,2011-02-05,2011-02-06,2011-02-07,...,2016-04-15,2016-04-16,2016-04-17,2016-04-18,2016-04-19,2016-04-20,2016-04-21,2016-04-22,2016-04-23,2016-04-24
unique_id,,,,,,,,,,,,,,,,,,,,,
HOBBIES_1_001_CA_1,0,0,0,0,0,0,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
HOBBIES_1_002_CA_1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
HOBBIES_1_003_CA_1,0,0,0,0,0,0,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
HOBBIES_1_004_CA_1,0,0,0,0,0,0,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
HOBBIES_1_005_CA_1,0,0,0,0,0,0,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4